spring:
  datasource:
    url: jdbc:mysql://${RDS_HOST}:${RDS:PORT}/${RDS_DATABASE}?autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull
    username: ${RDS_USER}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update